language: node_js
#install:
#  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha tests/**/**/*.js --report lcovonly -- -R spec && codecov
node_js:
  - 10.10.0
  - 8.40
  - 6.10